services:
  - type: web
    name: airline-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: bash -c "python manage.py migrate && gunicorn airline_system.wsgi:application --bind 0.0.0.0:$PORT"
