services:
  - type: web
    name: airline-system
    env: python
    plan: free
    buildCommand: ""
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: airline_system.settings
      - key: SECRET_KEY
        value: your-secret-key
