# Generated by Django 5.1.7 on 2025-05-03 19:01

import flights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default=flights.models.generate_booking_code, editable=False, max_length=6, unique=True),
        ),
    ]
